[features]
seeds = false
skip-lint = false
[programs.localnet]
counter = "9MGFR88uofDVcjHx3hoy2jmRtcnfMdQUbYRHCFFJFuXC"
hello_world = "A1zvqBnV7LPeCmSVg15CpFVUz8XEUh7aaGQwSB3WujgY"
lottery ="9FGeLV2TcxMR8sx8qjojzCU9Tk25NiUF1G9ZXDNjXy31"
[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
hello_world = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/hello_world.ts"
lottery = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/lottery.ts"
counter = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/counter.ts"